/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import ClassesBasicas.OrdemServico;
import Negocios.NegocioOrdemServico;
import java.awt.Color;
import java.awt.event.MouseEvent;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author Afonso
 */
public class CancelarSolucionarGUI extends javax.swing.JFrame {

    /**
     * Creates new form CancelarSolucionarGUI
     */
    ArrayList<OrdemServico> respostaOrdem = new ArrayList<>();
    public void ListarOrdem()
   
    {
        try
        {
            SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
            OrdemServico ordemServico = new OrdemServico();
            NegocioOrdemServico negocioOrdem = new NegocioOrdemServico();
            this.respostaOrdem = negocioOrdem.listarOrdemServicoAberta(ordemServico);
            DefaultTableModel modelo = new DefaultTableModel();
            modelo.setColumnIdentifiers(new Object[]{"Número", "Cliente", "CPF Cliente", "Funcionário", "Data de cadastro", "Problema"});
            
            for (OrdemServico os : this.respostaOrdem) 
            {
                modelo.addRow(new Object[]{os.getNumero(), os.getCliente().getNome(), os.getCliente().getCpf(), os.getFuncionario().getNome(), formato.format(os.getDataCadastro()), os.getClassificacaoProblema().getNomeClassProblema()});
            }
            jTableListarOrdem.setModel(modelo);
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(this, e.getMessage(), "ERRO", JOptionPane.ERROR_MESSAGE);
        }
    }
    public void DataAutomatica()
    {
        SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
        jTextFieldDataCadastro.setText(formato.format(new Date(System.currentTimeMillis())));
    }
    public CancelarSolucionarGUI() {
        initComponents();
        ListarOrdem();
        jButtonEditar.setEnabled(false);
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Ordens de Serviço", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 12), new java.awt.Color(0, 0, 0)));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 12), new java.awt.Color(0, 0, 0)));
        jPanel2.setBackground(Color.pink);
        jPanel1.setBackground(Color.pink);
        getContentPane().setBackground(Color.pink);
        DataAutomatica();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableListarOrdem = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldProcurarCliente = new javax.swing.JTextField();
        jButtonProcurarCliente = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldProcurarFuncionario = new javax.swing.JTextField();
        jButtonProcurarFuncionario = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldProcurarCPFCliente = new javax.swing.JTextField();
        jButtonCPFCliente = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButtonProcurarDataCadastro = new javax.swing.JButton();
        jTextFieldNumeroOrdem = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabelMotivo = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaMotivo = new javax.swing.JTextArea();
        jLabelData = new javax.swing.JLabel();
        jTextFieldDataCadastro = new javax.swing.JTextField();
        try
        {
            javax.swing.text.MaskFormatter data = new MaskFormatter("##/##/####");
            jTextFieldDataCadastro = new javax.swing.JFormattedTextField(data);
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        jButtonEditar = new javax.swing.JButton();
        jRadioButtonSolucionar = new javax.swing.JRadioButton();
        jRadioButtonCancelar = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTableListarOrdem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableListarOrdem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableListarOrdemMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTableListarOrdemMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTableListarOrdem);

        jLabel1.setText("Procurar Cliente");

        jButtonProcurarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens_Ícones/lupa (2).png"))); // NOI18N
        jButtonProcurarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonProcurarClienteActionPerformed(evt);
            }
        });

        jLabel2.setText("Procurar Funcionário");

        jButtonProcurarFuncionario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens_Ícones/lupa (2).png"))); // NOI18N
        jButtonProcurarFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonProcurarFuncionarioActionPerformed(evt);
            }
        });

        jLabel3.setText("Procurar CPF Cliente");

        jButtonCPFCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens_Ícones/lupa (2).png"))); // NOI18N
        jButtonCPFCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCPFClienteActionPerformed(evt);
            }
        });

        jLabel4.setText("Procurar Data de Cadastro");

        jButtonProcurarDataCadastro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens_Ícones/lupa (2).png"))); // NOI18N
        jButtonProcurarDataCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonProcurarDataCadastroActionPerformed(evt);
            }
        });

        jTextFieldNumeroOrdem.setEnabled(false);
        jTextFieldNumeroOrdem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNumeroOrdemActionPerformed(evt);
            }
        });

        jLabel5.setText("Nº Ordem");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 655, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextFieldProcurarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonProcurarCliente))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldProcurarFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonProcurarFuncionario)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(jTextFieldProcurarCPFCliente))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonProcurarDataCadastro)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButtonCPFCliente)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldNumeroOrdem, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jTextFieldProcurarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonProcurarCliente)
                            .addComponent(jLabel3)
                            .addComponent(jTextFieldProcurarCPFCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonCPFCliente))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTextFieldProcurarFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonProcurarFuncionario)
                            .addComponent(jLabel4)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonProcurarDataCadastro)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(208, 208, 208)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldNumeroOrdem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabelMotivo.setText("Motivo");

        jTextAreaMotivo.setColumns(20);
        jTextAreaMotivo.setRows(5);
        jScrollPane2.setViewportView(jTextAreaMotivo);

        jLabelData.setText("Data");

        jButtonEditar.setText("Ação");
        jButtonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButtonSolucionar);
        jRadioButtonSolucionar.setText("Solucionar");
        jRadioButtonSolucionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonSolucionarActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButtonCancelar);
        jRadioButtonCancelar.setText("Cancelar");
        jRadioButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabelMotivo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelData)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldDataCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonEditar)
                    .addComponent(jRadioButtonSolucionar)
                    .addComponent(jRadioButtonCancelar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelMotivo)
                    .addComponent(jLabelData)
                    .addComponent(jTextFieldDataCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jRadioButtonSolucionar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jRadioButtonCancelar)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonEditar))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(99, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTableListarOrdemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableListarOrdemMouseClicked
        MouseEvent e = evt;
        int click = e.getClickCount();
        int index = jTableListarOrdem.getSelectedRow();
        if(click == 2)
        {
            OrdemServico ordem = this.respostaOrdem.get(index);
            jTextFieldNumeroOrdem.setText(String.valueOf(ordem.getNumero()));
        }        
    }//GEN-LAST:event_jTableListarOrdemMouseClicked

    private void jTableListarOrdemMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableListarOrdemMousePressed
        jTableListarOrdem.editingCanceled(null);
        jTableListarOrdem.editingStopped(null);
    }//GEN-LAST:event_jTableListarOrdemMousePressed

    private void jRadioButtonSolucionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonSolucionarActionPerformed
        if(jRadioButtonSolucionar.isSelected() == true)
        {
            jButtonEditar.setEnabled(true);
            jButtonEditar.setText("Solucionar");
            jLabelMotivo.setText("Descrição do serviço");
        }
    }//GEN-LAST:event_jRadioButtonSolucionarActionPerformed

    private void jRadioButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonCancelarActionPerformed
        if(jRadioButtonCancelar.isSelected() == true)
        {
            jButtonEditar.setEnabled(true);
            jButtonEditar.setText("Cancelar");
            jLabelMotivo.setText("Motivo do cancelamento");
        }
    }//GEN-LAST:event_jRadioButtonCancelarActionPerformed

    private void jButtonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarActionPerformed
        if(jTextFieldNumeroOrdem.getText().equals(""))
        {
            JOptionPane.showMessageDialog(this, "Selecione a Ordem de Serviço", "Atenção", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        if(jRadioButtonCancelar.isSelected() == false && jRadioButtonSolucionar.isSelected() == false)
        {
            JOptionPane.showMessageDialog(this, "Selecione a ação desejada", "Atenção", JOptionPane.INFORMATION_MESSAGE);
        }
        if(jRadioButtonSolucionar.isSelected() == true)
        {
            try
            {
                OrdemServico ordemServico = new OrdemServico();
                SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
                Date dataCadastro = new java.sql.Date (formato.parse(jTextFieldDataCadastro.getText()).getTime());
                ordemServico.setNumero(Integer.parseInt(jTextFieldNumeroOrdem.getText()));
                ordemServico.setDescricaoServico(jTextAreaMotivo.getText());
                ordemServico.setDataSolucao(dataCadastro);
                NegocioOrdemServico negocioOrdem = new NegocioOrdemServico();
                negocioOrdem.solucionarOrdemServico(ordemServico);
                JOptionPane.showMessageDialog(this, "OS Solucionada", "Atenção", JOptionPane.INFORMATION_MESSAGE);
                ListarOrdem();
            }
            catch (Exception e)
            {
                JOptionPane.showMessageDialog(this, e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
            }
        }
        if(jRadioButtonCancelar.isSelected() == true)
        {
            try
            {
                OrdemServico ordemServico = new OrdemServico();
                SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
                Date dataCancelamento = new java.sql.Date (formato.parse(jTextFieldDataCadastro.getText()).getTime());
                ordemServico.setNumero(Integer.parseInt(jTextFieldNumeroOrdem.getText()));
                ordemServico.setMotivoCancelamento(jTextAreaMotivo.getText());
                ordemServico.setDatacancelamento(dataCancelamento);
                NegocioOrdemServico negocioOrdem = new NegocioOrdemServico();
                negocioOrdem.cancelarOrdemServico(ordemServico);
                JOptionPane.showMessageDialog(this, "OS Cancelada", "Atenção", JOptionPane.INFORMATION_MESSAGE);
                ListarOrdem();
            }
            catch (Exception e)
            {
                JOptionPane.showMessageDialog(this, e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_jButtonEditarActionPerformed

    private void jButtonProcurarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonProcurarClienteActionPerformed
        try
        {
            SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
            OrdemServico ordemServico = new OrdemServico();
            ordemServico.getCliente().setNome(jTextFieldProcurarCliente.getText());
            ordemServico.getCliente().setCpf(jTextFieldProcurarCPFCliente.getText());
            NegocioOrdemServico negocioOrdem = new NegocioOrdemServico();
            this.respostaOrdem = negocioOrdem.listarOrdemServicoAberta(ordemServico);
            DefaultTableModel modelo = new DefaultTableModel();
            modelo.setColumnIdentifiers(new Object[]{"Número", "Cliente", "CPF Cliente", "Funcionário", "Data de cadastro", "Problema"});
            
            for (OrdemServico os : this.respostaOrdem) 
            {
                modelo.addRow(new Object[]{os.getNumero(), os.getCliente().getNome(), os.getCliente().getCpf(), os.getFuncionario().getNome(), formato.format(os.getDataCadastro()), os.getClassificacaoProblema().getNomeClassProblema()});
            }
            jTableListarOrdem.setModel(modelo);
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonProcurarClienteActionPerformed

    private void jButtonCPFClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCPFClienteActionPerformed
        try
        {
            SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
            OrdemServico ordemServico = new OrdemServico();
            ordemServico.getCliente().setNome(jTextFieldProcurarCliente.getText());
            ordemServico.getCliente().setCpf(jTextFieldProcurarCPFCliente.getText());
            NegocioOrdemServico negocioOrdem = new NegocioOrdemServico();
            this.respostaOrdem = negocioOrdem.listarOrdemServicoAberta(ordemServico);
            DefaultTableModel modelo = new DefaultTableModel();
            modelo.setColumnIdentifiers(new Object[]{"Número", "Cliente", "CPF Cliente", "Funcionário", "Data de cadastro", "Problema"});
            
            for (OrdemServico os : this.respostaOrdem) 
            {
                modelo.addRow(new Object[]{os.getNumero(), os.getCliente().getNome(), os.getCliente().getCpf(), os.getFuncionario().getNome(), formato.format(os.getDataCadastro()), os.getClassificacaoProblema().getNomeClassProblema()});
            }
            jTableListarOrdem.setModel(modelo);
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonCPFClienteActionPerformed

    private void jButtonProcurarFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonProcurarFuncionarioActionPerformed
        try
        {
            SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
            OrdemServico ordemServico = new OrdemServico();
            ordemServico.getFuncionario().setNome(jTextFieldProcurarFuncionario.getText());
            NegocioOrdemServico negocioOrdem = new NegocioOrdemServico();
            this.respostaOrdem = negocioOrdem.listarOrdemServicoAberta(ordemServico);
            DefaultTableModel modelo = new DefaultTableModel();
            modelo.setColumnIdentifiers(new Object[]{"Número", "Cliente", "CPF Cliente", "Funcionário", "Data de cadastro", "Problema"});
            
            for (OrdemServico os : this.respostaOrdem) 
            {
                modelo.addRow(new Object[]{os.getNumero(), os.getCliente().getNome(), os.getCliente().getCpf(), os.getFuncionario().getNome(), formato.format(os.getDataCadastro()), os.getClassificacaoProblema().getNomeClassProblema()});
            }
            jTableListarOrdem.setModel(modelo);
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonProcurarFuncionarioActionPerformed

    private void jButtonProcurarDataCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonProcurarDataCadastroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonProcurarDataCadastroActionPerformed

    private void jTextFieldNumeroOrdemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNumeroOrdemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNumeroOrdemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CancelarSolucionarGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CancelarSolucionarGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CancelarSolucionarGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CancelarSolucionarGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CancelarSolucionarGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButtonCPFCliente;
    private javax.swing.JButton jButtonEditar;
    private javax.swing.JButton jButtonProcurarCliente;
    private javax.swing.JButton jButtonProcurarDataCadastro;
    private javax.swing.JButton jButtonProcurarFuncionario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelData;
    private javax.swing.JLabel jLabelMotivo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButtonCancelar;
    private javax.swing.JRadioButton jRadioButtonSolucionar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableListarOrdem;
    private javax.swing.JTextArea jTextAreaMotivo;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextFieldDataCadastro;
    private javax.swing.JTextField jTextFieldNumeroOrdem;
    private javax.swing.JTextField jTextFieldProcurarCPFCliente;
    private javax.swing.JTextField jTextFieldProcurarCliente;
    private javax.swing.JTextField jTextFieldProcurarFuncionario;
    // End of variables declaration//GEN-END:variables
}
