/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import ClassesBasicas.Funcionario;
import Negocios.NegocioFuncionario;
import java.awt.Color;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author aluno
 */
public class RemoverFuncionarioGUI extends javax.swing.JFrame {

    ArrayList<Funcionario> respostaFuncionario = new ArrayList<>();

    /**
     * Creates new form RemoverFuncionarioGUI
     */
    public void ListarCodMatricula() {
        try 
        {
            Funcionario funcionario = new Funcionario();
            NegocioFuncionario negocioFuncionario = new NegocioFuncionario();
            this.respostaFuncionario = negocioFuncionario.listarFuncionario(funcionario);
            DefaultTableModel modelo = new DefaultTableModel();
            modelo.setColumnIdentifiers(new Object[]{"Mátricula", "Nome", "CPF", "RG", "Salário"});
            
            for (Funcionario f : this.respostaFuncionario) 
            {
                modelo.addRow(new Object[]{f.getMatricula(), f.getNome(), f.getCpf(), f.getRg(), f.getSalario()});
            }
            jTable1.setModel(modelo);
        } 
        catch (Exception e) 
        {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }

    }

    public RemoverFuncionarioGUI() {
        initComponents();
        ListarCodMatricula();
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Ordens de Serviço", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 12), new java.awt.Color(0, 0, 0)));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Ordens de Serviço", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 12), new java.awt.Color(0, 0, 0)));
        jPanel2.setBackground(Color.pink);
        jPanel1.setBackground(Color.pink);
        getContentPane().setBackground(Color.pink);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jTextFieldProcurarNome = new javax.swing.JTextField();
        jLabelProcurarCPF = new javax.swing.JLabel();
        jTextFieldProcurarCPF = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldProcurarRG = new javax.swing.JTextField();
        jButtonListarNome = new javax.swing.JButton();
        jButtonListarCPF = new javax.swing.JButton();
        jButtonListarRG = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTable1MousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 626, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabelProcurarCPF.setText("Procurar por CPF");

        jLabel2.setText("Procurar por RG");

        jButtonListarNome.setText("Listar");
        jButtonListarNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonListarNomeActionPerformed(evt);
            }
        });

        jButtonListarCPF.setText("Listar");
        jButtonListarCPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonListarCPFActionPerformed(evt);
            }
        });

        jButtonListarRG.setText("Listar");
        jButtonListarRG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonListarRGActionPerformed(evt);
            }
        });

        jLabel1.setText("Procurar por Nome");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(23, 23, 23)
                        .addComponent(jTextFieldProcurarRG))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabelProcurarCPF)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldProcurarCPF))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldProcurarNome, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonListarNome)
                    .addComponent(jButtonListarCPF)
                    .addComponent(jButtonListarRG))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldProcurarNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonListarNome))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelProcurarCPF)
                    .addComponent(jTextFieldProcurarCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonListarCPF))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldProcurarRG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonListarRG))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(135, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        MouseEvent e = evt;
        int click = e.getClickCount();
        int index = jTable1.getSelectedRow();
        if (click == 2)
        {
            try 
            {
                Funcionario funcionario = this.respostaFuncionario.get(index);
                String mensagem = "Deseja remover este funcionário?\nFuncionário: " + funcionario.getNome() + "\nCPF: " + funcionario.getCpf() + "\nRG :" + funcionario.getRg();
                int resultado = JOptionPane.showConfirmDialog(this, mensagem, "Remover funcionário", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
                if(resultado == JOptionPane.YES_OPTION)
                {
                    NegocioFuncionario negocioFuncionario = new NegocioFuncionario();
                    negocioFuncionario.excluirFuncionario(funcionario);
                    ListarCodMatricula();
                    JOptionPane.showMessageDialog(this, "Funcionário removido", "Aviso", JOptionPane.INFORMATION_MESSAGE);
                }            
            }
            catch (Exception ex) 
            {
                JOptionPane.showMessageDialog(this, ex.getMessage(), "Atenção", JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void jTable1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MousePressed
        jTable1.editingCanceled(null);
        jTable1.editingStopped(null);
    }//GEN-LAST:event_jTable1MousePressed

    private void jButtonListarNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonListarNomeActionPerformed
        try
            {
                Funcionario funcionario = new Funcionario();
                funcionario.setNome(jTextFieldProcurarNome.getText());
                funcionario.setCpf(jTextFieldProcurarCPF.getText());
                funcionario.setRg(jTextFieldProcurarRG.getText());
                NegocioFuncionario negocioFuncionario = new NegocioFuncionario();
                this.respostaFuncionario = negocioFuncionario.listarFuncionario(funcionario);
                DefaultTableModel modelo = new DefaultTableModel();
                modelo.setColumnIdentifiers(new Object[]{"Mátricula", "Nome", "CPF", "RG", "Salário"});
            
                for (Funcionario f : this.respostaFuncionario) 
                {
                    modelo.addRow(new Object[]{f.getMatricula(), f.getNome(), f.getCpf(), f.getRg(), f.getSalario()});
                }
                jTable1.setModel(modelo);
                }
                catch (Exception e)
                {
                    JOptionPane.showMessageDialog(this, e.getMessage(), "Atenção", JOptionPane.WARNING_MESSAGE);
                }
    }//GEN-LAST:event_jButtonListarNomeActionPerformed

    private void jButtonListarCPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonListarCPFActionPerformed
        try
            {
                Funcionario funcionario = new Funcionario();
                funcionario.setNome(jTextFieldProcurarNome.getText());
                funcionario.setCpf(jTextFieldProcurarCPF.getText());
                funcionario.setRg(jTextFieldProcurarRG.getText());
                NegocioFuncionario negocioFuncionario = new NegocioFuncionario();
                this.respostaFuncionario = negocioFuncionario.listarFuncionario(funcionario);
                DefaultTableModel modelo = new DefaultTableModel();
                modelo.setColumnIdentifiers(new Object[]{"Mátricula", "Nome", "CPF", "RG", "Salário"});
            
                for (Funcionario f : this.respostaFuncionario) 
                {
                    modelo.addRow(new Object[]{f.getMatricula(), f.getNome(), f.getCpf(), f.getRg(), f.getSalario()});
                }
                jTable1.setModel(modelo);
            }
            catch (Exception e)
            {
                JOptionPane.showMessageDialog(this, e.getMessage(), "Atenção", JOptionPane.WARNING_MESSAGE);
            }
    }//GEN-LAST:event_jButtonListarCPFActionPerformed

    private void jButtonListarRGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonListarRGActionPerformed
            try
            {
                Funcionario funcionario = new Funcionario();
                funcionario.setNome(jTextFieldProcurarNome.getText());
                funcionario.setCpf(jTextFieldProcurarCPF.getText());
                funcionario.setRg(jTextFieldProcurarRG.getText());
                NegocioFuncionario negocioFuncionario = new NegocioFuncionario();
                this.respostaFuncionario = negocioFuncionario.listarFuncionario(funcionario);
                DefaultTableModel modelo = new DefaultTableModel();
                modelo.setColumnIdentifiers(new Object[]{"Mátricula", "Nome", "CPF", "RG", "Salário"});
            
                for (Funcionario f : this.respostaFuncionario) 
                {
                    modelo.addRow(new Object[]{f.getMatricula(), f.getNome(), f.getCpf(), f.getRg(), f.getSalario()});
                }
                jTable1.setModel(modelo);
            }
            catch (Exception e)
            {
                JOptionPane.showMessageDialog(this, e.getMessage(), "Atenção", JOptionPane.WARNING_MESSAGE);
            }
    }//GEN-LAST:event_jButtonListarRGActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RemoverFuncionarioGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RemoverFuncionarioGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RemoverFuncionarioGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RemoverFuncionarioGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RemoverFuncionarioGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonListarCPF;
    private javax.swing.JButton jButtonListarNome;
    private javax.swing.JButton jButtonListarRG;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelProcurarCPF;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextFieldProcurarCPF;
    private javax.swing.JTextField jTextFieldProcurarNome;
    private javax.swing.JTextField jTextFieldProcurarRG;
    // End of variables declaration//GEN-END:variables
}
