/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import ClassesBasicas.OrdemServico;
import Negocios.NegocioOrdemServico;
import java.awt.event.MouseEvent;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author aluno
 */
public class RemoverOrdemGUI extends javax.swing.JFrame {

    /**
     * Creates new form RemoverOrdemGUI
     */
    ArrayList<OrdemServico> respostaOrdem = new ArrayList<>();
    public void ListarOrdem()
    {
        try
        {
            SimpleDateFormat formato2 = new SimpleDateFormat("dd/MM/yyyy");
            OrdemServico ordemServico = new OrdemServico();
            NegocioOrdemServico negocioOrdem = new NegocioOrdemServico();
            this.respostaOrdem = negocioOrdem.listarOrdemServicoAberta(ordemServico);
            DefaultTableModel modelo = new DefaultTableModel();
            modelo.setColumnIdentifiers(new Object[]{"Cliente", "CPF Cliente", "Funcionário", "Data de cadastro", "Problema"});
            
            for (OrdemServico os : this.respostaOrdem) 
            {
                modelo.addRow(new Object[]{os.getCliente().getNome(), os.getCliente().getCpf(), os.getFuncionario().getNome(), formato2.format(os.getDataCadastro()), os.getClassificacaoProblema().getNomeClassProblema()});
            }
            jTable1.setModel(modelo);
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(this, e.getMessage(), "ERRO", JOptionPane.ERROR_MESSAGE);
        }
    }
    public RemoverOrdemGUI() {
        initComponents();
        ListarOrdem();
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Ordens de Serviço", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 12), new java.awt.Color(0, 0, 0)));
        setLocationRelativeTo(this);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabelCliente = new javax.swing.JLabel();
        jTextFieldProcurarCliente = new javax.swing.JTextField();
        jButtonCliente = new javax.swing.JButton();
        jLabelCPFCliente = new javax.swing.JLabel();
        jTextFieldProcurarCPFCliente = new javax.swing.JTextField();
        jButtonProcurarCPFCliente = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldProcurarFuncionario = new javax.swing.JTextField();
        jButtonProcurarFuncionario = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldProcurarData = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTable1MousePressed(evt);
            }
        });
        jTable1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTable1KeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabelCliente.setText("Procurar Cliente");

        jButtonCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens_Ícones/lupa (2).png"))); // NOI18N
        jButtonCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClienteActionPerformed(evt);
            }
        });

        jLabelCPFCliente.setText("Procurar CPF Cliente");

        jButtonProcurarCPFCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens_Ícones/lupa (2).png"))); // NOI18N
        jButtonProcurarCPFCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonProcurarCPFClienteActionPerformed(evt);
            }
        });

        jLabel1.setText("Procurar Funcionário");

        jButtonProcurarFuncionario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens_Ícones/lupa (2).png"))); // NOI18N
        jButtonProcurarFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonProcurarFuncionarioActionPerformed(evt);
            }
        });

        jLabel2.setText("Procurar Data de Cadastro");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens_Ícones/lupa (2).png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 676, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabelCliente))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jTextFieldProcurarFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonProcurarFuncionario))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jTextFieldProcurarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonCliente)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabelCPFCliente))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldProcurarCPFCliente)
                            .addComponent(jTextFieldProcurarData, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonProcurarCPFCliente)
                            .addComponent(jButton1))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCliente)
                    .addComponent(jTextFieldProcurarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCliente)
                    .addComponent(jLabelCPFCliente)
                    .addComponent(jTextFieldProcurarCPFCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonProcurarCPFCliente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldProcurarFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonProcurarFuncionario)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldProcurarData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MousePressed
        jTable1.editingCanceled(null);
        jTable1.editingStopped(null);
    }//GEN-LAST:event_jTable1MousePressed

    private void jTable1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable1KeyTyped
        jTable1.editingCanceled(null);
        jTable1.editingStopped(null);
    }//GEN-LAST:event_jTable1KeyTyped

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        MouseEvent e = evt;
        int click = e.getClickCount();
        int index = jTable1.getSelectedRow(); 
        OrdemServico os = this.respostaOrdem.get(index);
        if(click == 2)
        {
            String mensagem = "Deseja remover esta OS?\nNúmero: " + os.getNumero() + "\nCliente: " + os.getCliente().getNome()+ "\nFuncionário: " + os.getFuncionario().getNome();
            int resposta = JOptionPane.showConfirmDialog(this, mensagem, "Remover", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            if(resposta == JOptionPane.YES_OPTION)
            {
                try
                {
                    OrdemServico ordemServico = new OrdemServico();
                    ordemServico.setNumero(os.getNumero());
                    NegocioOrdemServico negocioOrdem = new NegocioOrdemServico();
                    negocioOrdem.removerOrdemServico(ordemServico);
                    JOptionPane.showMessageDialog(this, "OS Removida", "Atenção", JOptionPane.INFORMATION_MESSAGE);
                    ListarOrdem();
                }
                catch (Exception ex)
                {
                    JOptionPane.showMessageDialog(this, ex.getMessage(), "ERRO", JOptionPane.ERROR_MESSAGE);
                }
            }           
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButtonClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClienteActionPerformed
        try
        {
            SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
            OrdemServico ordemServico = new OrdemServico();
            ordemServico.getCliente().setNome(jTextFieldProcurarCliente.getText());
            ordemServico.getCliente().setCpf(jTextFieldProcurarCPFCliente.getText());
            ordemServico.getFuncionario().setNome(jTextFieldProcurarFuncionario.getText());
            NegocioOrdemServico negocioOrdem = new NegocioOrdemServico();
            this.respostaOrdem = negocioOrdem.listarOrdemServicoAberta(ordemServico);
            DefaultTableModel modelo = new DefaultTableModel();
            modelo.setColumnIdentifiers(new Object[]{"Cliente", "CPF Cliente", "Funcionário", "Data de cadastro", "Problema"});
            
            for (OrdemServico os : this.respostaOrdem) 
            {
                modelo.addRow(new Object[]{os.getCliente().getNome(), os.getCliente().getCpf(), os.getFuncionario().getNome(), formato.format(os.getDataCadastro()), os.getClassificacaoProblema().getNomeClassProblema()});
            }
            
            jTable1.setModel(modelo);
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonClienteActionPerformed

    private void jButtonProcurarFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonProcurarFuncionarioActionPerformed
        try
        {
            SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
            OrdemServico ordemServico = new OrdemServico();
            ordemServico.getCliente().setNome(jTextFieldProcurarCliente.getText());
            ordemServico.getCliente().setCpf(jTextFieldProcurarCPFCliente.getText());
            ordemServico.getFuncionario().setNome(jTextFieldProcurarFuncionario.getText());
            NegocioOrdemServico negocioOrdem = new NegocioOrdemServico();
            this.respostaOrdem = negocioOrdem.listarOrdemServicoAberta(ordemServico);
            DefaultTableModel modelo = new DefaultTableModel();
            modelo.setColumnIdentifiers(new Object[]{"Cliente", "CPF Cliente", "Funcionário", "Data de cadastro", "Problema"});
            
            for (OrdemServico os : this.respostaOrdem) 
            {
                modelo.addRow(new Object[]{os.getCliente().getNome(), os.getCliente().getCpf(), os.getFuncionario().getNome(), formato.format(os.getDataCadastro()), os.getClassificacaoProblema().getNomeClassProblema()});
            }
            
            jTable1.setModel(modelo);
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonProcurarFuncionarioActionPerformed

    private void jButtonProcurarCPFClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonProcurarCPFClienteActionPerformed
        try
        {
            SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
            OrdemServico ordemServico = new OrdemServico();
            ordemServico.getCliente().setNome(jTextFieldProcurarCliente.getText());
            ordemServico.getCliente().setCpf(jTextFieldProcurarCPFCliente.getText());
            ordemServico.getFuncionario().setNome(jTextFieldProcurarFuncionario.getText());
            NegocioOrdemServico negocioOrdem = new NegocioOrdemServico();
            this.respostaOrdem = negocioOrdem.listarOrdemServicoAberta(ordemServico);
            DefaultTableModel modelo = new DefaultTableModel();
            modelo.setColumnIdentifiers(new Object[]{"Cliente", "CPF Cliente", "Funcionário", "Data de cadastro", "Problema"});
            
            for (OrdemServico os : this.respostaOrdem) 
            {
                modelo.addRow(new Object[]{os.getCliente().getNome(), os.getCliente().getCpf(), os.getFuncionario().getNome(), formato.format(os.getDataCadastro()), os.getClassificacaoProblema().getNomeClassProblema()});
            }
            
            jTable1.setModel(modelo);
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonProcurarCPFClienteActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RemoverOrdemGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RemoverOrdemGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RemoverOrdemGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RemoverOrdemGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RemoverOrdemGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonCliente;
    private javax.swing.JButton jButtonProcurarCPFCliente;
    private javax.swing.JButton jButtonProcurarFuncionario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelCPFCliente;
    private javax.swing.JLabel jLabelCliente;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextFieldProcurarCPFCliente;
    private javax.swing.JTextField jTextFieldProcurarCliente;
    private javax.swing.JTextField jTextFieldProcurarData;
    private javax.swing.JTextField jTextFieldProcurarFuncionario;
    // End of variables declaration//GEN-END:variables
}
